// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3RNDHI9twTT9pNo5MGNrwfJko27xvo0c',
    appId: '1:216440811936:web:e650430da969fede3574c5',
    messagingSenderId: '216440811936',
    projectId: 'projekt-konrad-klima-pam',
    authDomain: 'projekt-konrad-klima-pam.firebaseapp.com',
    storageBucket: 'projekt-konrad-klima-pam.firebasestorage.app',
    measurementId: 'G-QG9FNEEG1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkcv2w6vEMSNG0Qo4Mt-3-Hqo9sTVRvMo',
    appId: '1:216440811936:android:5077772c9090423b3574c5',
    messagingSenderId: '216440811936',
    projectId: 'projekt-konrad-klima-pam',
    storageBucket: 'projekt-konrad-klima-pam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD68U73HV-OndlklZF5GFT04rEufis-phE',
    appId: '1:216440811936:ios:7452bd26f8441e2d3574c5',
    messagingSenderId: '216440811936',
    projectId: 'projekt-konrad-klima-pam',
    storageBucket: 'projekt-konrad-klima-pam.firebasestorage.app',
    iosBundleId: 'com.example.lotrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD68U73HV-OndlklZF5GFT04rEufis-phE',
    appId: '1:216440811936:ios:7452bd26f8441e2d3574c5',
    messagingSenderId: '216440811936',
    projectId: 'projekt-konrad-klima-pam',
    storageBucket: 'projekt-konrad-klima-pam.firebasestorage.app',
    iosBundleId: 'com.example.lotrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3RNDHI9twTT9pNo5MGNrwfJko27xvo0c',
    appId: '1:216440811936:web:4fcffab38e320f143574c5',
    messagingSenderId: '216440811936',
    projectId: 'projekt-konrad-klima-pam',
    authDomain: 'projekt-konrad-klima-pam.firebaseapp.com',
    storageBucket: 'projekt-konrad-klima-pam.firebasestorage.app',
    measurementId: 'G-5MRT8LHMDP',
  );
}
